window.CBME_QUOTE_DATA = {
  company: {
    name: "Costa Brava Music Events",
    tagline: "Musica, so i il·luminació per a casaments i esdeveniments",
    email: "info@costabravamusicevents.com",
    phones: ["687 962 905", "619 840 206"],
    instagram: "@costabrava_music_events",
    logo: "../assets/img/logo-hero-white-text.png",
  },
  auth: {
    passwordHash: "707067a11c5e67cf0f79fc6ec38f9719fe89564ee8e9770d19d8034bdb5e0fdb",
    sessionKey: "cbme-quotes-unlocked",
  },
  copy: {
    ca: {
      tagline: "Música, so i il·luminació per a casaments i esdeveniments",
      technicalProposal: "Proposta tècnica i musical",
      quote: "Pressupost",
      number: "Número",
      date: "Data",
      validUntil: "Valid fins",
      personalizedProposal: "Proposta personalitzada",
      client: "Client",
      pendingClient: "Client pendent",
      eventPlace: "Espai",
      guests: "Convidats",
      undefined: "Per definir",
      totalProposal: "Total proposta",
      deposit: "Paga i senyal aprox.",
      pending: "Import pendent",
      service: "Servei",
      qty: "Quant.",
      price: "Preu",
      total: "Total",
      terms: "Condicions",
      subtotal: "Subtotal",
      tax: "IVA 21%",
      copied: "Copiat",
      copySummary: "Copiar resum",
      customName: "Servei personalitzat",
      customDescription: "Descripció del servei.",
      plusTax: " + IVA si correspon",
      taxIncluded: " IVA inclòs",
    },
    es: {
      tagline: "Música, sonido e iluminación para bodas y eventos",
      technicalProposal: "Propuesta técnica y musical",
      quote: "Presupuesto",
      number: "Número",
      date: "Fecha",
      validUntil: "Válido hasta",
      personalizedProposal: "Propuesta personalizada",
      client: "Cliente",
      pendingClient: "Cliente pendiente",
      eventPlace: "Espacio",
      guests: "Invitados",
      undefined: "Por definir",
      totalProposal: "Total propuesta",
      deposit: "Reserva aprox.",
      pending: "Importe pendiente",
      service: "Servicio",
      qty: "Cant.",
      price: "Precio",
      total: "Total",
      terms: "Condiciones",
      subtotal: "Subtotal",
      tax: "IVA 21%",
      copied: "Copiado",
      copySummary: "Copiar resumen",
      customName: "Servicio personalizado",
      customDescription: "Descripción del servicio.",
      plusTax: " + IVA si corresponde",
      taxIncluded: " IVA incluido",
    },
    en: {
      tagline: "Music, sound and lighting for weddings and events",
      technicalProposal: "Technical and musical proposal",
      quote: "Quote",
      number: "Number",
      date: "Date",
      validUntil: "Valid until",
      personalizedProposal: "Personalized proposal",
      client: "Client",
      pendingClient: "Client pending",
      eventPlace: "Venue",
      guests: "Guests",
      undefined: "To be confirmed",
      totalProposal: "Proposal total",
      deposit: "Approx. deposit",
      pending: "Pending amount",
      service: "Service",
      qty: "Qty.",
      price: "Price",
      total: "Total",
      terms: "Terms",
      subtotal: "Subtotal",
      tax: "VAT 21%",
      copied: "Copied",
      copySummary: "Copy summary",
      customName: "Custom service",
      customDescription: "Service description.",
      plusTax: " + VAT if applicable",
      taxIncluded: " VAT included",
    },
  },
  taxRate: 0.21,
  depositRate: 1 / 3,
  catalog: [
    {
      group: "Paquets base",
      items: [
        {
          id: "pack-boda-mitja",
          name: "Pack boda format mitjà",
          description: "So principal, DJ, coordinació musical i suport tècnic per a una boda de format mitjà.",
          price: 1450,
        },
        {
          id: "pack-boda-gran",
          name: "Pack boda format gran",
          description: "Produccio ampliada per a celebracions grans amb reforc de so, subgreus i tècnica dedicada.",
          price: 1850,
        },
        {
          id: "pack-dj-festa",
          name: "Sessió DJ festa",
          description: "Sessió DJ de 3 hores amb preparació musical prèvia.",
          price: 420,
        },
      ],
    },
    {
      group: "So",
      items: [
        {
          id: "so-cerimònia",
          name: "So cerimònia",
          description: "2 altaveus, mesclador/control de so, micro de peu i micro inalàmbric.",
          price: 265,
        },
        {
          id: "so-aperitiu",
          name: "So aperitiu",
          description: "2 altaveus i control de so per a aperitiu o coctel.",
          price: 160,
        },
        {
          id: "so-menjadors",
          name: "So menjador",
          description: "4 altaveus, mesclador/control de so i micro inalàmbric.",
          price: 280,
        },
        {
          id: "so-mitja-rcf",
          name: "Equip de so format mitjà RCF",
          description: "Equip 6000 W RCF amb 2 subgreus, 2 tops i 2 monitors.",
          price: 1250,
        },
        {
          id: "so-gran-rcf",
          name: "Equip de so format gran RCF",
          description: "Equip 10000 W RCF amb 4 subgreus, 6 tops i 2 monitors.",
          price: 1550,
        },
      ],
    },
    {
      group: "Il·luminació",
      items: [
        {
          id: "llums-disco",
          name: "So i llums disco",
          description: "Stand DJ, 2 altaveus + subgreu, truss, 4 wash, 6 moving heads, fum i 2 totems.",
          price: 800,
        },
        {
          id: "llums-mitja",
          name: "Il·luminació boda format mitjà",
          description: "4 gobos, 4 totems de truss, 6 PAR LED, taula de llums i maquina de fum.",
          price: 1280,
        },
        {
          id: "jardi-leds",
          name: "Corredor de leds jardi",
          description: "Linia decorativa de leds per a entrada, jardi o zona exterior.",
          price: 180,
        },
        {
          id: "sostre-leds",
          name: "Sostre de leds",
          description: "Instal.lacio decorativa de sostre de leds.",
          price: 1015,
        },
        {
          id: "focus-led",
          name: "12 focus LED color 35 W",
          description: "Il·luminació ambiental per a jardi, menjador o parets.",
          price: 85,
        },
      ],
    },
    {
      group: "Extres",
      items: [
        {
          id: "dj-extra-hour",
          name: "Hora extra DJ",
          description: "Hora extra quan se superen les hores contractades.",
          price: 120,
        },
        {
          id: "foc-fred-8",
          name: "Foc fred 8 bengales",
          description: "8 bengales de foc fred, duracio aproximada 30 segons.",
          price: 280,
        },
        {
          id: "foc-fred-2",
          name: "Foc fred 2 maquines",
          description: "2 maquines de foc fred, duracio aproximada 8 minuts.",
          price: 330,
        },
        {
          id: "projector",
          name: "Projector + pantalla",
          description: "Projector 3000 lumens i pantalla de 240 cm.",
          price: 175,
        },
        {
          id: "bombolles-fum",
          name: "Maquina de bombolles de fum",
          description: "Efecte recomanat per a entrada, ball o moment especial.",
          price: 85,
        },
        {
          id: "bola-miralls",
          name: "Bola de miralls 50 cm",
          description: "Element visual per a pista de ball o zona disco.",
          price: 110,
        },
      ],
    },
    {
      group: "Produccio",
      items: [
        {
          id: "personal-tècnic",
          name: "Personal tècnic",
          description: "Muntatge, proves, operacio tècnica i desmuntatge.",
          price: 450,
        },
        {
          id: "transport",
          name: "Transport",
          description: "Transport de material dins zona Costa Brava / Girona.",
          price: 150,
        },
      ],
    },
  ],
  templates: [
    {
      id: "boda-mitja",
      name: "Boda format mitjà",
      eventType: "Boda",
      intro: "Proposta de so, il·luminació i DJ per cobrir els moments principals del casament amb una producció clara i adaptable a l'espai.",
      itemIds: ["so-cerimònia", "so-aperitiu", "so-menjadors", "llums-disco", "pack-dj-festa"],
    },
    {
      id: "boda-gran",
      name: "Boda format gran",
      eventType: "Boda",
      intro: "Proposta reforcada per a casaments amb volum d'assistents alt, diferents espais i necessitat de mes pressio sonora.",
      itemIds: ["so-gran-rcf", "llums-mitja", "pack-dj-festa", "transport"],
    },
    {
      id: "so-mitja",
      name: "Només so format mitjà",
      eventType: "Esdeveniment privat",
      intro: "Pressupost tècnic per a sonoritzacio de format mitjà amb equip RCF, monitors i personal de muntatge.",
      itemIds: ["so-mitja-rcf"],
    },
    {
      id: "iluminacio-mitja",
      name: "Il·luminació format mitjà",
      eventType: "Boda",
      intro: "Proposta d'il·luminació decorativa i de pista per crear ambient durant sopar, moments especials i festa.",
      itemIds: ["llums-mitja"],
    },
  ],
  defaultTerms: [
    "Preus sense IVA. S'aplicara el 21% d'IVA si correspon.",
    "La reserva es formalitza amb una paga i senyal aproximada d'un terc del total.",
    "El preu inclou preparació previa, coordinació musical i seguiment fins al dia de l'esdeveniment.",
    "Transport, personal i muntatge inclòsos nomes quan apareixen indicats al pressupost.",
    "Si un espai no s'ha de sonoritzar o una partida no s'utilitza, es pot retirar del pressupost.",
    "El dinar o sopar de l'equip tècnic/DJ va a càrrec del client quan el servei coincideix amb l'àpat.",
  ],
  localizedTerms: {
    ca: [
      "Preus sense IVA. S'aplicarà el 21% d'IVA si correspon.",
      "La reserva es formalitza amb una paga i senyal aproximada d'un terç del total.",
      "El preu inclou preparació prèvia, coordinació musical i seguiment fins al dia de l'esdeveniment.",
      "Transport, personal i muntatge inclosos només quan apareixen indicats al pressupost.",
      "Si un espai no s'ha de sonoritzar o una partida no s'utilitza, es pot retirar del pressupost.",
      "El dinar o sopar de l'equip tècnic/DJ va a càrrec del client quan el servei coincideix amb l'àpat.",
    ],
    es: [
      "Precios sin IVA. Se aplicará el 21% de IVA si corresponde.",
      "La reserva se formaliza con una paga y señal aproximada de un tercio del total.",
      "El precio incluye preparación previa, coordinación musical y seguimiento hasta el día del evento.",
      "Transporte, personal y montaje incluidos solo cuando aparecen indicados en el presupuesto.",
      "Si un espacio no debe sonorizarse o una partida no se utiliza, se puede retirar del presupuesto.",
      "La comida o cena del equipo técnico/DJ corre a cargo del cliente cuando el servicio coincide con la comida.",
    ],
    en: [
      "Prices exclude VAT. 21% VAT will be applied when applicable.",
      "The booking is confirmed with an approximate one-third deposit.",
      "The price includes prior preparation, musical coordination and follow-up until the event date.",
      "Transport, staff and setup are included only when listed in the quote.",
      "If an area does not require sound or an item is not used, it can be removed from the quote.",
      "Meals for the technical/DJ team are covered by the client when the service overlaps with lunch or dinner.",
    ],
  },
  groups: {
    ca: {
      "Paquets base": "Paquets base",
      So: "So",
      "Il·luminació": "Il·luminació",
      Extres: "Extres",
      Produccio: "Producció",
    },
    es: {
      "Paquets base": "Paquetes base",
      So: "Sonido",
      "Il·luminació": "Iluminación",
      Extres: "Extras",
      Produccio: "Producción",
    },
    en: {
      "Paquets base": "Base packages",
      So: "Sound",
      "Il·luminació": "Lighting",
      Extres: "Extras",
      Produccio: "Production",
    },
  },
  itemCopy: {
    "pack-boda-mitja": {
      es: ["Pack boda formato medio", "Sonido principal, DJ, coordinación musical y soporte técnico para una boda de formato medio."],
      en: ["Medium wedding package", "Main sound system, DJ, musical coordination and technical support for a medium-format wedding."],
    },
    "pack-boda-gran": {
      es: ["Pack boda formato grande", "Producción ampliada para celebraciones grandes con refuerzo de sonido, subgraves y técnica dedicada."],
      en: ["Large wedding package", "Expanded production for larger celebrations with sound reinforcement, subwoofers and dedicated technical support."],
    },
    "pack-dj-festa": {
      es: ["Sesión DJ fiesta", "Sesión DJ de 3 horas con preparación musical previa."],
      en: ["DJ party session", "3-hour DJ session with prior music preparation."],
    },
    "so-cerimònia": {
      es: ["Sonido ceremonia", "2 altavoces, mezclador/control de sonido, micrófono de pie y micrófono inalámbrico."],
      en: ["Ceremony sound", "2 speakers, mixer/sound control, stand microphone and wireless microphone."],
    },
    "so-aperitiu": {
      es: ["Sonido aperitivo", "2 altavoces y control de sonido para aperitivo o cóctel."],
      en: ["Cocktail sound", "2 speakers and sound control for cocktail hour or aperitif."],
    },
    "so-menjadors": {
      es: ["Sonido comedor", "4 altavoces, mezclador/control de sonido y micrófono inalámbrico."],
      en: ["Dining area sound", "4 speakers, mixer/sound control and wireless microphone."],
    },
    "so-mitja-rcf": {
      es: ["Equipo de sonido formato medio RCF", "Equipo 6000 W RCF con 2 subgraves, 2 tops y 2 monitores."],
      en: ["Medium RCF sound system", "6000 W RCF system with 2 subwoofers, 2 tops and 2 monitors."],
    },
    "so-gran-rcf": {
      es: ["Equipo de sonido formato grande RCF", "Equipo 10000 W RCF con 4 subgraves, 6 tops y 2 monitores."],
      en: ["Large RCF sound system", "10000 W RCF system with 4 subwoofers, 6 tops and 2 monitors."],
    },
    "llums-disco": {
      es: ["Sonido y luces disco", "Stand DJ, 2 altavoces + subgrave, truss, 4 wash, 6 moving heads, humo y 2 tótems."],
      en: ["Party sound and lighting", "DJ stand, 2 speakers + subwoofer, truss, 4 wash lights, 6 moving heads, smoke and 2 totems."],
    },
    "llums-mitja": {
      es: ["Iluminación boda formato medio", "4 gobos, 4 tótems de truss, 6 PAR LED, mesa de luces y máquina de humo."],
      en: ["Medium wedding lighting", "4 gobos, 4 truss totems, 6 LED PARs, lighting desk and smoke machine."],
    },
    "jardi-leds": {
      es: ["Pasillo de leds jardín", "Línea decorativa de leds para entrada, jardín o zona exterior."],
      en: ["Garden LED walkway", "Decorative LED line for entrance, garden or outdoor area."],
    },
    "sostre-leds": {
      es: ["Techo de leds", "Instalación decorativa de techo de leds."],
      en: ["LED ceiling", "Decorative LED ceiling installation."],
    },
    "focus-led": {
      es: ["12 focos LED color 35 W", "Iluminación ambiental para jardín, comedor o paredes."],
      en: ["12 color LED spots 35 W", "Ambient lighting for garden, dining area or walls."],
    },
    "dj-extra-hour": {
      es: ["Hora extra DJ", "Hora extra cuando se superan las horas contratadas."],
      en: ["Extra DJ hour", "Extra hour when the contracted time is exceeded."],
    },
    "foc-fred-8": {
      es: ["Fuego frío 8 bengalas", "8 bengalas de fuego frío, duración aproximada 30 segundos."],
      en: ["Cold sparks 8 fountains", "8 cold spark fountains, approximately 30 seconds."],
    },
    "foc-fred-2": {
      es: ["Fuego frío 2 máquinas", "2 máquinas de fuego frío, duración aproximada 8 minutos."],
      en: ["Cold sparks 2 machines", "2 cold spark machines, approximately 8 minutes."],
    },
    projector: {
      es: ["Proyector + pantalla", "Proyector 3000 lumens y pantalla de 240 cm."],
      en: ["Projector + screen", "3000-lumen projector and 240 cm screen."],
    },
    "bombolles-fum": {
      es: ["Máquina de burbujas de humo", "Efecto recomendado para entrada, baile o momento especial."],
      en: ["Smoke bubble machine", "Recommended effect for entrance, first dance or special moment."],
    },
    "bola-miralls": {
      es: ["Bola de espejos 50 cm", "Elemento visual para pista de baile o zona disco."],
      en: ["50 cm mirror ball", "Visual element for the dance floor or party area."],
    },
    "personal-tècnic": {
      es: ["Personal técnico", "Montaje, pruebas, operación técnica y desmontaje."],
      en: ["Technical staff", "Setup, testing, technical operation and teardown."],
    },
    transport: {
      es: ["Transporte", "Transporte de material dentro de la zona Costa Brava / Girona."],
      en: ["Transport", "Equipment transport within the Costa Brava / Girona area."],
    },
  },
  templateCopy: {
    "boda-mitja": {
      es: ["Boda formato medio", "Boda", "Propuesta de sonido, iluminación y DJ para cubrir los momentos principales de la boda con una producción clara y adaptable al espacio."],
      en: ["Medium wedding", "Wedding", "Sound, lighting and DJ proposal covering the main wedding moments with a clear production setup adapted to the venue."],
    },
    "boda-gran": {
      es: ["Boda formato grande", "Boda", "Propuesta reforzada para bodas con alto número de invitados, diferentes espacios y necesidad de mayor presión sonora."],
      en: ["Large wedding", "Wedding", "Reinforced proposal for weddings with a high guest count, multiple areas and stronger sound requirements."],
    },
    "so-mitja": {
      es: ["Solo sonido formato medio", "Evento privado", "Presupuesto técnico para sonorización de formato medio con equipo RCF, monitores y personal de montaje."],
      en: ["Sound only medium format", "Private event", "Technical quote for medium-format sound reinforcement with RCF system, monitors and setup staff."],
    },
    "iluminacio-mitja": {
      es: ["Iluminación formato medio", "Boda", "Propuesta de iluminación decorativa y de pista para crear ambiente durante cena, momentos especiales y fiesta."],
      en: ["Medium lighting", "Wedding", "Decorative and dance-floor lighting proposal to create atmosphere during dinner, special moments and the party."],
    },
  },
};
